#%RAML 1.0 NamedExample

value:
-
  id: "1"
  firstname: "vin"
  lastname: "diesel"
  address: "112 west street"
  postal: " 12334"
  country: "united states of america"
  miles: 600
  creationdate: 2024-03-09T12:00:00Z
  type: "personal"
-
  id: "2"
  firstname: "steve"
  lastname: "roger"
  address: "113 washington st"
  postal: "12345"
  country: "united states of america"
  miles: 600
  creationdate: 2024-03-09T12:00:00Z
  type:  "personal"