#%RAML 1.0 NamedExample

value:
-
  firstname: "vin"
  lastname: "diesel"
  address: "112 west street"
  postal: "12334"
  country: "united states of america"
  miles: 600
  type: "personal"
-
  firstname: "steve"
  lastname: "roger"
  address: "113 washington st"
  postal: "12345"
  country: "united states of america"
  miles: 600
  type: "personal"
