#%RAML 1.0 DataType
displayName: ACCOUNTS
description: DATA-TYPE OF THE ACCOUNTS

type: object
properties:
  id?: string
  firstname: string
  lastname: string
  address: string
  postal: string
  country: string
  miles: integer
  creationdate?: datetime
  type: string
  


